#!/bin/bash
mv ~/.profile ~/.profile.bak

ln -s ~/.dot/profile.osx ~/.profile
ln -s ~/.dot/zprofile ~/.zprofile
ln -s ~/.dot/zshrc ~/.zshrc
ln -s ~/.dot/oh-my-zsh/ ~/.oh-my-zsh

ln -s ~/.dot/vim/ ~/.vim
ln -s ~/.dot/vimrc ~/.vimrc
ln -s ~/.dot/gvimrc ~/.gvimrc

ln -s ~/.dot/tmux.osx ~/.tmux.conf

ln -s ~/.dot/gitconfig ~/.gitconfig
ln -s ~/.dot/gitignore ~/.gitignore

ln -s ~/.dot/ipython_config.py ~/.ipython/profile_default/ipython_config.py
