#!/bin/bash

ln -s ~/.dot/profile.debian ~/.profile
ln -s ~/.dot/zprofile ~/.zprofile
ln -s ~/.dot/zshrc ~/.zshrc
ln -s ~/.dot/oh-my-zsh/ ~/.oh-my-zsh

ln -s ~/.dot/vim/ ~/.vim
ln -s ~/.dot/vimrc ~/.vimrc
ln -s ~/.dot/gvimrc ~/.gvimrc

ln -s ~/.dot/tmux.debian ~/.tmux.conf

ln -s ~/.dot/gitconfig ~/.gitconfig
ln -s ~/.dot/gitignore ~/.gitignore

ln -s ~/.dot/noserc ~/.noserc
ln -s ~/.dot/config/flake8 ~/.config/flake8
ln -s ~/.dot/ipython_config.py ~/.ipython/profile_default/ipython_config.py
