#!/bin/bash
while getopts "v:" opt; do
    case $opt in
        v)
            source $OPTARG/bin/activate
            ;;
    esac
done

shift $(($OPTIND-1))
edit_pane=$1

echo -en "\033]2;ipython\\033\\"
ipython
tmux send-keys -t $edit_pane ":call semicolon#restart_ipython()" C-m
