#!/bin/bash
function finalize {
    clear
    echo -en '\n[ Debug ]'
}

close=true
while getopts "xov:" opt; do
    case $opt in
        x)
            sleep 1
            finalize
            exit 1
            ;;

        o)
            close=false
            ;;
        v)
            source $OPTARG/bin/activate
            ;;
    esac
done

shift $(($OPTIND-1))
edit_pane=$1
shift 1

echo -en "\033]2;debug\\033\\"
$@
echo -e '\033[0;32m\nPress ANY KEY to continue.\033[0m'
read -n 1

finalize 

if $close; then
    tmux send-keys -t $edit_pane ":call semicolon#close_console()" C-m
else
    tmux select-pane -t $edit_pane
fi
